### ISSUE TITLE
Opening excel files

### ISSUE THREAD

**Issue by Diederiki** [winfsp/sshfs-win#116]
I have  implemented sshfs on enterprise level and manage everything with Cerberus FTP.
Now we are facing issues when trying to directly open excel files from the mapped sshfs drive and modify them.
It won't open, file explorer crash when opening excel files. and we also can't save excel files directly to the server, it saves only  a 0 kb file.
I also noticed that Nitro PDF is not compatitable with sshfs too. When opening a PDF file, modify it and directly save it back to the drive cause Nitro to crash.
But I figured out that it does work with Adobe Acrobat Pro.

We used the latest stable versions 2019.2 with Windows 10 1809 & 1903
The server that I map with sshfs is Windows server 2019

**Comment by Diederiki** [comment]
Yeah I tried that at first and smaller excel files can be opened (very slow) but saving back to drive never works. Ik stores a temp file and a 1 or 0 kb file.

**Comment by Diederiki** [comment]
I have been testing with Mountain Duck and that works perfect with opening and saving excel files to the server. However, thats a expensive solution.

**Comment by B4rt0** [comment]
As far as I know once you open Excel file on network share it gets locked for editing for other users. This issue may be related to that feature. There may be workaround for that - https://support.office.com/en-us/article/about-the-shared-workbook-feature-49b833c0-873b-48d8-8bf2-c1c59a628534

**Comment by ioweb-gr** [comment]
I've been struggling with this for a while too. I can't make it work

**Comment by Diederiki** [comment]
Ah this is an old topic, we are using Raidrive for the past 2 years which works the best from our experience and is free too.
Raidrive uses Rebex ssh which is very fast.
