### ISSUE TITLE
Can read, can write, can't execute

### ISSUE THREAD

**Issue by StagnationPoint** [winfsp/sshfs-win#132]
Love this software, many thanks for your hard work on it!

I am mounting a Linux Mint 19.2 host (based on Ubuntu 18.04). WinFsp 2019.2, SSHFS-Win (x64) 2.7.17334 installed via choco.

I can mount the share, navigate to a folder with a binary. Reading is fine, writing is fine. But if I try to execute the binary through the mount from cmd, I get: "Access is denied."

I can copy the binary to my Windows desktop, and it runs from there just fine. Here's my fsptool-x64.exe output for the .exe:

O:S-1-5-21-3719583759-2467315270-3514381345-1001G:S-1-5-1000D:P(A;;0x1f019f;;;S-1-5-21-3719583759-2467315270-3514381345-1001)(A;;FR;;;S-1-5-1000)(A;;FR;;;WD) (perm=197609:1000:0644)

The Windows host is 2019 LTSC. It is not part of a domain, doesn't have a group policy imposed on it, etc.

Now, important note: On linux, the .exe's permissions are 644. If I change them to 755, then I can start it on Windows, but then I get a dialog with the following error:

"The application was unable to start correctly (0xc0000022). Click OK to close the application."

Internet searching indicates this is likely a permissions problem, but it doesn't help me resolve the issue.

Again, if I copy the binary (and the dependencies in its folder) to the Windows desktop, it runs fine from there.

Any advice would be appreciated. Thanks again for sshfs-win!

**Comment by billziss-gh** [comment]
SSHFS-Win by default respects the permissions set on the SSHFS server. So if the permissions are `0644` (`rw-r--r--`) the file is not considered executable.

When you change it to `0755` (`rwxr-xr-x`) the file now becomes executable. The error `0xc0000022` is `STATUS_ACCESS_DENIED`. This may mean that your program needs a DLL or other executable that does not have the proper permissions either.

**Comment by StagnationPoint** [comment]
You mention "by default respects the permissions." Is there an override I might be interested in that allows any .exe to be considered executable? I tried adding exec to the mount options, but that didn't seem to make a difference.

**Comment by billziss-gh** [comment]
Yes, there is. Try adding the `-o unmask=755`, which will make all files executable by everyone.
