### ISSUE TITLE
File modified timestamp not respected

### ISSUE THREAD

**Issue by AtmanActive** [winfsp/sshfs-win#288]
Unfortunately, SSHFS-WIN + WinFsp does NOT respect file modified timestamp when copying files TO a SFTP server.

My scenario: two windows machines, one serving a drive via OpenSSH 8.1, the other mounted that same drive via SSHFS-WIN + WinFsp. When I copy some files from the client machine to the server machine, the files do appear on the server machine but they all have modified timestamp set to now. In other words, the original modified timestamp in the file itself is lost. [BAD]

Now, when I dismount the drive from SSHFS-WIN + WinFsp and mount it with Mountainduck (on the same machine) and repeat the same operation (simple copy+paste in two separate windows explorer windows), all files are copied and their modified timestamps are untouched. Meaning, on the server, the files now have exactly the same modified timestamps as on the client. [GOOD]

Hence, SSHFS-WIN and/or WinFsp can be considered buggy or unfinished in this regard.

**Comment by billziss-gh** [comment]
I believe this may be related to this problem billziss-gh/winfsp#362. A fix for this problem is already in the development branch and should appear in the next WinFsp release.

**Comment by AtmanActive** [comment]
That's great news!
Thank you very much.

**Comment by AtmanActive** [comment]
I believe this to be fixed as of 2023-04-27, latest WinFSP.
