### ISSUE TITLE
Load key "/cygdrive/c/**/.ssh/id_rsa": invalid format

### ISSUE THREAD

**Issue by Cyl18** [winfsp/sshfs-win#293]
![image](https://user-images.githubusercontent.com/14993992/120887975-822e5c80-c628-11eb-835f-6f8d00f40f0e.png)
file format: 
![image](https://user-images.githubusercontent.com/14993992/120887926-2f54a500-c628-11eb-84f8-4540c6390d9d.png)
key file type is ED25519, and I can use the key file from windows's ssh (e.g. from powershell: `ssh cyl18@some.server`)

**Comment by rhyst** [comment]
I had this issue and I replaced all the windows line endings `\n\r` with just linux line endings `\n` and it then worked

**Comment by keldian** [comment]
Add a single line feed (i.e. press Enter) at the end of the file.
