### ISSUE TITLE
Can't show the image after opening

### ISSUE THREAD

**Issue by qiaomu-miao** [winfsp/sshfs-win#309]
Hi, I am trying to use sshfs-win to view images on an ssh server. After mounting, it can show the large icon view of the images in the folder, but after double-clicking the image, it shows nothing but blank, like the screenshot shown below. May I know the reason of this and how can I fix this?

![image](https://user-images.githubusercontent.com/18041918/133000897-9e4d4a69-2be4-416d-9426-119aa1a14dd4.png)

Thanks very much!

**Comment by Rho1Cancri** [comment]
I hope my post over there can provide further info, as I encountered the same problem.

**Comment by Noexpert** [comment]
I've repaired and reset the Win 10 Photos App (I'm not using the old Windows Photo Viewer, referred to, above), but the issue persists. I can view photos in other viewers such as FastStone.

**Comment by billziss-gh** [comment]
I believe I have addressed this issue in WinFsp commit billziss-gh/winfsp@cf13cac43813c41f66e34d27155d25c90f795b7c.

Unfortunately I am not certain when I will be making a new release with this fix.

**Comment by Noexpert** [comment]
> I believe I have addressed this issue in WinFsp commit [billziss-gh/winfsp@cf13cac](https://github.com/billziss-gh/winfsp/commit/cf13cac43813c41f66e34d27155d25c90f795b7c).
> 
> Unfortunately I am not certain when I will be making a new release with this fix.

Bill, thanks.
No urgency, as long as it's being addressed.
