### ISSUE TITLE
UNC syntax to specify key?

### ISSUE THREAD

**Issue by Noexpert** [winfsp/sshfs-win#339]
I'm able to connect by mapping a network drive using UNC syntax.
I'm also able to connect using SSHF-Win Manager using a custom key location with the `-oIdentityFile=` flag.

How can I use a custom key with UNC?

Looking at the UNC syntax, I don't see an option to specify a key:
`\\sshfs.kr\[LOCUSER=]REMUSER@HOST[!PORT][\PATH]`

I'm aware of https://github.com/winfsp/sshfs-win/issues/231, but that seems to be for `svc`

Also related:
https://github.com/winfsp/sshfs-win/issues/320
https://github.com/winfsp/sshfs-win/issues/323

**Comment by Noexpert** [comment]
Thanks for your post.

Do you know how to use that config file with UNC syntax?
`\\sshfs.kr\[LOCUSER=]REMUSER@HOST[!PORT][\PATH]`

Thanjs

**Comment by BrianMarre** [comment]
Yes, you replace HOST with the new name <alias> you gave your remote server in the config file.

For example, if the following is the entry in your config file and your private key file is "C:\Users\userLocal\.ssh\remoteServerKey"
´´´
Host remoteServer
    Hostname remoteServer@example.com
    User user1
    IdentityFile C:\Users\userLocal\.ssh\remoteServerKey
    IdentitiesOnly yes
´´´
Then you would specify that as "\\sshfs.k\user1@remoteServer", port and remote path can be added as usual.

**Comment by Noexpert** [comment]
Thanks.

I saved the config file here: `C:\Users\User\.ssh\config`
```
Host user1_server
    Hostname hostname.domain.com
    User user1
    IdentityFile C:\Users\User\.ssh\user1
    IdentitiesOnly yes
```

I then attempt to map a new network drive in Windows Explorer: `\\sshfs.kr\user1@user1_server!XXXX\path\`, but it fails.
Am I using wrong syntax somewhere?

**Comment by Noexpert** [comment]
The solution is here:
https://github.com/winfsp/sshfs-win/issues/155#issuecomment-1316261288
