### ISSUE TITLE
Feature request: Importing/Loading an existing sshfs-win-manager configuration

### ISSUE THREAD

**Issue by jo-chemla** [winfsp/sshfs-win#435]
It can be useful for users to load an entire existing sshfs-win-manager configuration to a new instance of sshfs-win-manager, eg on another computer. 
Power users can probably edit and copy-paste the content of the `\AppData\Roaming\sshfs-win-manager\vuex.json`, but for non-techies it could be useful to allow for importing of an existing configuration - exporting it could also be useful, but can be handled by an admin.

**Comment by billziss-gh** [comment]
This looks like it is sshfs-win-manager related so please repost this request there.

https://github.com/evsar3/sshfs-win-manager/issues

**Comment by jo-chemla** [comment]
Woops indeed sorry I thought I as on their repo!
